baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Deep Learning'
theme =  "hugo-book"

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = 'monokailight'
